# Generated by Django 4.2.1 on 2023-06-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вопрос')),
                ('var1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вариант 1')),
                ('var2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вариант 2')),
                ('var3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вариант 3')),
                ('var4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вариант 4')),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Правильный ответ')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.theme', verbose_name='Тест')),
            ],
            options={
                'verbose_name': '1. Вопрос теста',
                'verbose_name_plural': '1. Вопросы тестов',
                'ordering': ['theme'],
            },
        ),
    ]
