# Generated by Django 4.2.1 on 2023-06-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Пиши в дательном падеже <br>С маленькой буквы', max_length=50, verbose_name='Уроки по')),
                ('serial', models.IntegerField(default='1', unique=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': '1. Тема урока',
                'verbose_name_plural': '1. Темы уроков',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название урока', help_text='С маленькой буквы', max_length=50, verbose_name='Название урока')),
                ('text', models.TextField(default='<p>Текст урока</p>', help_text='Пиши используя HTML тэги, через них происходит конвертация стиля.<br> <_p><_/p> для обычного абзаца. <br> <_img src="/media/FILENAME.png"> для изображения. <br> <_ul><_li><_/li><_/li> для формата списка. <br> <_container-images><_/container-images> для создания контейнера с 2-я изображениями. <br> <_long-image-near-text> для 2-х изображений рядом с текстом. Внутри для изображений <_container-images-block><_img><_img><_/container-images-block>, а для текста обычный абзац <_p>', verbose_name='Урок')),
                ('serial', models.IntegerField(default='1', verbose_name='Порядковый номер урока')),
                ('publish', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('preview_image_url', models.CharField(default='<img src="static/preview_empty-tag.png">', max_length=50, verbose_name='Ссылка на превью в текстовом виде')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.theme', verbose_name='Уроки по')),
            ],
            options={
                'verbose_name': '2. Урок',
                'verbose_name_plural': '2. Уроки',
                'ordering': ['publish'],
            },
        ),
    ]
